[supervisord]
nodaemon=true
user=root

[program:Xvfb]
command=/usr/bin/Xvfb :1 -screen 0 1776x999x24
autostart=true
autorestart=true
priority=10

[program:vnc]
command=/bin/start_vnc.sh
autostart=true
autorestart=true
priority=20

[program:fluxbox]
command=/usr/bin/fluxbox
environment=DISPLAY=":1"
autostart=true
autorestart=true
priority=30

[program:novnc]
command=/opt/novnc/utils/novnc_proxy --vnc localhost:5901 --listen 6080
autostart=true
autorestart=true
priority=50
